tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"

# brew "anyenv"
# brew "awscli"
# brew "bash-completion"
brew "python"
brew "direnv"
brew "docker", link: false
brew "ffmpeg"
brew "git"
brew "go"
brew "lynx"
brew "mas"
brew "mono"
brew "mysql"
brew "nkf"
brew "nmap"
brew "node"
brew "postgresql"
brew "telnet"
brew "tree"
brew "vim"
brew "yarn", link: false
brew "heroku/brew/heroku"

cask "bitwarden"
cask "cheatsheet"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-hackgen"
cask "fujitsu-scansnap-home"
cask "google-japanese-ime"
cask "hyper"
cask "karabiner-elements"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "vagrant"
cask "slack"
cask "gimp"
cask "google-chrome"
cask "postman"
cask "skype"
cask "visual-studio-code"
cask "kindle"
