[tools]
awscli = ['latest']
go = ['latest']
# heroku-cli = ['latest']
nodejs = ['latest', 'lts']
ruby = ['latest', '2.7.8']
php = ['latest', '7.4.33']
terraform = ['latest', '1.0.5', '1.3.1', '1.3.3', '1.3.4', '1.3.6', '1.3.7']
[settings]
jobs = 4
experimental = true
