[tools]
#awscli = ['latest']
go = ['latest']
# heroku-cli = ['latest']
node = ['latest', 'lts', "14", "16"]
ruby = ['latest', '2.7.8']
python = ['3.9']
php = ['latest', '7.4.33']
terraform = "1.5.1"
[settings]
jobs = 4
experimental = true
