# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"
[templates]
fpath-file = 'fpath=( {% for file in files %} "{{ file }}" {% endfor %} $fpath )'
add-function ='{{name}}() { {% for file in files %} {{ file }} {% endfor%} }'
fpath-completion-zsh = "fpath=({{ dir }}/completion/zsh $fpath )"
fpath-completions = "fpath=({{ dir }}/completions $fpath )"

[plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
[plugins.yadm]
#remote = 'https://raw.githubusercontent.com/TheLocehiliosan/yadm/master/completion/zsh/_yadm'
#use = ["completion/zsh"]
#apply = ["fpath-file"]
github = "TheLocehiliosan/yadm"
apply = [ "fpath-completion-zsh", "path" ]

[plugins.asdf]
github = "asdf-vm/asdf"
use = ["asdf.sh"]
apply = [ "fpath-completions", "source" ]

[plugins.sheldon-completion]
inline = """
ZSH_COMPLETION_DIR="$HOME/.local/share/zsh/completions"
if ! [ -e "$ZSH_COMPLETION_DIR/_sheldon" ]; then
  mkdir -p "$ZSH_COMPLETION_DIR"
  sheldon completions --shell zsh > "$ZSH_COMPLETION_DIR/_sheldon"
fi
fpath=($ZSH_COMPLETION_DIR $fpath)
"""
