#!/bin/bash -e

if [ "$MEMO_REPO_HOST" = "" ]; then
  MEMO_REPO_HOST="github.com"
fi
if [ "$MEMO_REPO_USER" = "" ]; then
  MEMO_REPO_USER="yammerjp"
fi
if [ "$MEMO_REPO_REPONAME" = "" ]; then
  MEMO_REPO_REPONAME="memo"
fi
if [ "$GIT_REPOS_BASE_DIR" = "" ]; then
  GIT_REPOS_BASE_DIR="$HOME/src"
fi
if [ "$MEMO_REPO_DAYLOG_DIR" = "" ]; then
  MEMO_REPO_DAYLOG_DIR="daylog"
fi
if [ "$MEMO_DATE_FORMAT" = "" ]; then
  MEMO_DATE_FORMAT='+%Y%m%d'
fi

MEMO_REPO_DIR="$GIT_REPOS_BASE_DIR/$MEMO_REPO_HOST/$MEMO_REPO_USER/$MEMO_REPO_REPONAME"

if ! [ -e $MEMO_REPO_DIR ]; then
  git clone "git@$MEMO_REPO_HOST:$MEMO_REPO_USER/$MEMO_REPO_REPONAME.git" "$MEMO_REPO_DIR"
fi

DAYLOG_DIR="$MEMO_REPO_DIR/$MEMO_REPO_DAYLOG_DIR"
mkdir -p "DAYLOG_DIR"

if command -v gdate > /dev/null; then
  DATECMD="gdate"
else
  DATECMD="date"
fi

if command -v bat > /dev/null; then
  CATCMD="bat"
else
  CATCMD="cat"
fi

if [ "$1" = prev ] || [ "$1" = p ]; then
  FILENAME="$($DATECMD --date "$2 day ago" $MEMO_DATE_FORMAT ).md"
elif [ "$1" = next ] || [ "$1" = n ]; then
  FILENAME="$($DATECMD --date "$2 day" $MEMO_DATE_FORMAT ).md"
elif [ "$1" = list ] || [ "$1" = l ]; then
  vim "$(find "$DAYLOG_DIR" -type f | fzf --preview "$CATCMD {}")"
  return
else
  FILENAME="$($DATECMD $MEMO_DATE_FORMAT ).md"
fi
exec nvim "$DAYLOG_DIR/$FILENAME"
