name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run : |
        sudo apt-get install shellcheck
        sudo apt-get install zsh

    - name: Check '*.sh'
      run : find ${GITHUB_WORKSPACE} -type f | grep -E "\.sh$" | grep -v 'download-install-mini.sh' | xargs shellcheck

   # - name: Check .zprofile
   #   run : zsh -n ${GITHUB_WORKSPACE}/.zprofile

   # - name: Check '.zshrc*'
   #   run : find ${GITHUB_WORKSPACE} -type f | grep -E "zshrc" | xargs shellcheck

