name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run : |
        sudo apt-get install shellcheck
        sudo apt-get install zsh

    - name: Check '*.sh'
      run : .github/scripts/lint.sh

   # - name: Check .zprofile
   #   run : zsh -n ${GITHUB_WORKSPACE}/.zprofile

   # - name: Check '.zshrc*'
   #   run : find ${GITHUB_WORKSPACE} -type f | grep -E "zshrc" | xargs shellcheck

