name: macOS Setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-setup:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Mask Homebrew package list
      run : |
        sed -i '' '/^cask /d' ${GITHUB_WORKSPACE}/.config/homebrew/package-list-darwin-x86_64
        sed -i '' '/^mas /d'  ${GITHUB_WORKSPACE}/.config/homebrew/package-list-darwin-x86_64

    - name: Run
      run : |
        DOTFILES_DIR="${GITHUB_WORKSPACE}" ./setup.sh

    # Use error.log. Not be able to use 'set -e' in .zprofile
    #- name: Load .zprofile
    #  run : |
    #    touch error.log
    #    zsh ~/.zprofile 2> error.log
    #    cat error.log
    #    if [ -s error.log ]; then false; fi

    ## Use error.log. Not be able to use 'set -e' in .zshrc
    #- name: Load .zshrc
    #  run : |
    #    touch error.log
    #    zsh ~/.zshrc 2> error.log
    #    cat error.log
    #    if [ -s error.log ]; then false; fi

