name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Unit Test
      run : find ${GITHUB_WORKSPACE}/test -type f | xargs -IXXX bash XXX

