name: Ubuntu Setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy
      run : |
        mkdir -p ~/src/github.com/yammerjp
        cp -r ${GITHUB_WORKSPACE} ~/src/github.com/yammerjp

    - name: Run
      run : |
        cd ~/src/github.com/yammerjp/dotfiles/bin
        ./dotfiles link
        ./dotfiles setup

    # Use error.log. Not be able to use 'set -e' in .zprofile
    # - name: Load .zprofile
    #   run : |
    #     touch error.log
    #     zsh ~/.zprofile 2> error.log
    #     cat error.log
    #     if [ -s error.log ]; then false; fi

    # Use error.log. Not be able to use 'set -e' in .zshrc
    # - name: Load .zshrc
    #   run : |
    #     touch error.log
    #     zsh ~/.zshrc 2> error.log
    #     cat error.log
    #     if [ -s error.log ]; then false; fi

